USER-SUPPLIED VALUES:
clusterName: hs-eks-cluster
hyperswitch-app:
  application:
    server:
      basilisk:
        host: basilisk-host
      locker:
        hyperswitch_private_key: locker-key
        locker_readonly_key: locker-key
      master_enc_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAElxqCFjue+Lpitt3a6IkgUAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCJKUO73GHcYnr51twIBEIBbpU8MP7RObiMkN7M9wBldxTfN2+7Ieq70DLEA72DU5z/jlZcQszuYqn0qsJ16sO4dsk8PHG31lRMeqkuZsmmlN8rLZWEDooxCvlu9fMDekxnvvaBXKycoGdfP5g==
      secrets:
        admin_api_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAEVKLoXIazbnORPTzbiXVLRAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMq+/3dvUCdzeGaILTAgEQgCVaXDLHxpKloWO7+OLbf7j4zlH5n7CLniXNTk9Wh4rBKNduH6QJ
        api_hash_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAGzcKkdCGYWifXqcGtIiAXzAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDrG9AiqEbZo4CKtFAIBEIBb1VpAvk1dGAlePAHcJOgb04+olH8EhVwGySiuU/N/MLibRepAUkGrcCb/60OlWliVNAQ0Hj8ahncY+nq7Xr4ncTQBCTR++uL1XrGJ7zM3FoTIOxb4gAT5jj6+PA==
        apple_pay_merchant_cert: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        apple_pay_merchant_cert_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        apple_pay_merchant_conf_merchant_cert: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        apple_pay_merchant_conf_merchant_cert_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        apple_pay_merchant_conf_merchant_id: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        apple_pay_ppc: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        apple_pay_ppc_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        forex_api_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        forex_fallback_api_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        jwt_secret: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAENRDUYyvtNCzg6/mneAEtYAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMo/tRPQi7HuaJGIv/AgEQgCUsO4UQTEMyTjciQ5IvPeBlR10fkfg2wnj9sUpWIgix+5sButYE
        kms_admin_api_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAEVKLoXIazbnORPTzbiXVLRAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMq+/3dvUCdzeGaILTAgEQgCVaXDLHxpKloWO7+OLbf7j4zlH5n7CLniXNTk9Wh4rBKNduH6QJ
        kms_connector_onboarding_paypal_client_id: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_connector_onboarding_paypal_client_secret: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_connector_onboarding_paypal_partner_id: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_encrypted_api_hash_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAGzcKkdCGYWifXqcGtIiAXzAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDrG9AiqEbZo4CKtFAIBEIBb1VpAvk1dGAlePAHcJOgb04+olH8EhVwGySiuU/N/MLibRepAUkGrcCb/60OlWliVNAQ0Hj8ahncY+nq7Xr4ncTQBCTR++uL1XrGJ7zM3FoTIOxb4gAT5jj6+PA==
        kms_jwekey_locker_decryption_key1: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_locker_decryption_key2: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_locker_encryption_key1: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_locker_encryption_key2: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_locker_identifier1: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_locker_identifier2: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_rust_locker_encryption_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_tunnel_private_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        kms_jwekey_vault_encryption_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAEeFRffMgtFGTq0LfvT9tE7AAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbBsaPpa6Nol34oYvAgEQgCXdfIaKzrJaauRU4qmunN4loRUBsDhD/jOD00h+zRtYmOha29q3
        kms_jwekey_vault_private_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFAZygKzvM2t/gV8tlAgForAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMgIuQlkZZY86Nvs/AgEQgCXHVg5wWBko6y+/cDDuz+c3sxpkKuFnHQoFEFbCRAHJtTnXxbYA
        kms_jwt_secret: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAENRDUYyvtNCzg6/mneAEtYAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMo/tRPQi7HuaJGIv/AgEQgCUsO4UQTEMyTjciQ5IvPeBlR10fkfg2wnj9sUpWIgix+5sButYE
        kms_key_id: 5c88f6dc-4772-42fa-b41b-c3bfad06dedc
        kms_key_region: us-east-1
        pm_auth_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
        podAnnotations:
          traffic_sidecar_istio_io_excludeOutboundIPRanges: 10.23.6.12/32
        recon_admin_api_key: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAFE2MpKFdab5eKrKZwNPv11AAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBDtZgCTY1K0GEv5mAgEQgCTQjkaHIxi51EcIK8ZjzxiDUUEdHUZrF+gND3Zgh1rjUdzinKQ=
      secrets_manager: aws_kms
      server_base_url: https://sandbox.hyperswitch.io
      serviceAccountAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::225681119357:role/hyperswitch-HyperswitchServiceAccountRoleCC06B446-EfTLI7eNXJet
  autoscaling:
    enabled: true
    maxReplicas: 5
    minReplicas: 3
    targetCPUUtilizationPercentage: 80
  externalPostgresql:
    enabled: true
    primary:
      auth:
        database: hyperswitch
        password: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAF6vTm2QWKAcnxzfJz5P693AAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMB6RGFuFAThE7DbcAgEQgCML+QQMYgmslRE35VRa3jBMgCJPYZAVCCePyiuLaNjT6NhjTg==
        plainpassword: Camel123
        username: db_user
      host: hyperswitch-hyperswitchdbcluster6afb6ee5-wruvqfstcsya.cluster-ccpofvgo2wzr.us-east-1.rds.amazonaws.com
    readOnly:
      auth:
        database: hyperswitch
        password: AQICAHiZzvr2eAKNcPSi2yi2GGWe4lGa2PeQpe/NpmqjuOp8xAF6vTm2QWKAcnxzfJz5P693AAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMB6RGFuFAThE7DbcAgEQgCML+QQMYgmslRE35VRa3jBMgCJPYZAVCCePyiuLaNjT6NhjTg==
        plainpassword: Camel123
        username: db_user
      host: hyperswitch-hyperswitchdbcluster6afb6ee5-wruvqfstcsya.cluster-ro-ccpofvgo2wzr.us-east-1.rds.amazonaws.com
  externalRedis:
    enabled: true
    host: hs-elasticache.4x7hjl.0001.use1.cache.amazonaws.com
    port: 6379
  hyperswitch-card-vault:
    enabled: false
    postgresql:
      enabled: false
    server:
      secrets:
        locker_private_key: ""
        master_key: ""
        tenant_public_key: ""
  loadBalancer:
    targetSecurityGroup: sg-0a8d906b47becbb9e
  postgresql:
    enabled: false
  redis:
    enabled: false
  services:
    consumer:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-consumer:v1.107.0-standalone
    controlCenter:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-control-center:v1.29.9
    producer:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-producer:v1.107.0-standalone
    router:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-router:v1.107.0-standalone
    sdk:
      host: http://localhost:9090
      subversion: v0
      version: 0.27.2
hyperswitchsdk:
  autoBuild:
    forceBuild: true
    gitCloneParam:
      gitVersion: 0.27.2
    nginxConfig:
      extraPath: v0
  enabled: true
  ingress:
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
      alb.ingress.kubernetes.io/group.name: hyperswitch-web-alb-ingress-group
      alb.ingress.kubernetes.io/ip-address-type: ipv4
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/load-balancer-name: hyperswitch-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: sg-0a8d906b47becbb9e
      alb.ingress.kubernetes.io/tags: stack=hyperswitch-lb
      alb.ingress.kubernetes.io/target-type: ip
    className: alb
    hosts:
    - host: ""
      paths:
      - path: /
        pathType: Prefix
  loadBalancer:
    targetSecurityGroup: sg-0a8d906b47becbb9e
  services:
    router:
      host: http://localhost:8080
    sdkDemo:
      hyperswitchPublishableKey: pub_key
      hyperswitchSecretKey: secret_key
      image: juspaydotin/hyperswitch-web:v1.27.2
loadBalancer:
  targetSecurityGroup: sg-0a8d906b47becbb9e
