USER-SUPPLIED VALUES:
clusterName: hs-eks-cluster
hyperswitch-app:
  application:
    server:
      basilisk:
        host: basilisk-host
      locker:
        hyperswitch_private_key: locker-key
        locker_readonly_key: locker-key
      master_enc_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAG35h1ageO3GzkAGaQx8rK0AAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDD//bTBCCfFDvp2AoQIBEIBbUZsGsSgAtTTq54TSmxTbPMTeW8eOAJ78LjXUeQk/TtvZL8rq54DdTGm8/30SqtxhkCFl/nr0VQaS1PYlDm0yan1PHL+ABJ+wBRIo8z16JKnJhvf/wJldHpLzhA==
      secrets:
        admin_api_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFQ534Wh7rzztJQ5VRyONI6AAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTdv8jcXH60zJC6oqAgEQgCXm+FVDiX2sAHJ6fRYFGloVnms0DfVYzHhVhCes6o5b4z9ESl49
        api_hash_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAE/2+lpKSEpz/z2CngQBXrKAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMJofGE3NygYUraKUAIBEIBb0LHP245D+HkZuw1+LtZODz23qqWhB3d6UpngxKYMp18P0jgOPs64piDRu1Wo35Qkgsntq2kaQ66KCyKnnJg7RTG/2sE8IhVd+4oUJ4fdKYVrukB2lduZO9Jquw==
        apple_pay_merchant_cert: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        apple_pay_merchant_cert_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        apple_pay_merchant_conf_merchant_cert: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        apple_pay_merchant_conf_merchant_cert_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        apple_pay_merchant_conf_merchant_id: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        apple_pay_ppc: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        apple_pay_ppc_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        forex_api_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        forex_fallback_api_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        jwt_secret: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtmdnaT88qTqx34LFathd3AAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3FRTY1cSscoJ3RJXAgEQgCXSj1b6K5hdYdxvAF+VrpU//BJlg219NiTLIVwW1oDHTASAk8wn
        kms_admin_api_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFQ534Wh7rzztJQ5VRyONI6AAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTdv8jcXH60zJC6oqAgEQgCXm+FVDiX2sAHJ6fRYFGloVnms0DfVYzHhVhCes6o5b4z9ESl49
        kms_connector_onboarding_paypal_client_id: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_connector_onboarding_paypal_client_secret: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_connector_onboarding_paypal_partner_id: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_encrypted_api_hash_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAE/2+lpKSEpz/z2CngQBXrKAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMJofGE3NygYUraKUAIBEIBb0LHP245D+HkZuw1+LtZODz23qqWhB3d6UpngxKYMp18P0jgOPs64piDRu1Wo35Qkgsntq2kaQ66KCyKnnJg7RTG/2sE8IhVd+4oUJ4fdKYVrukB2lduZO9Jquw==
        kms_jwekey_locker_decryption_key1: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_locker_decryption_key2: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_locker_encryption_key1: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_locker_encryption_key2: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_locker_identifier1: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_locker_identifier2: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_rust_locker_encryption_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_tunnel_private_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        kms_jwekey_vault_encryption_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAE7FhpDZE89S1P1gHbcv93rAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9sRJxpSJ0l0NnUZLAgEQgCXDvUK3XvlM3uJnwYQwbDBudDr9x5oTGJqxX2bHPW9efFnKvgnZ
        kms_jwekey_vault_private_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFN8NfAot7VoCjbQ5UHz9/EAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGY18t2pTT3mvLztaAgEQgCX02pHVBE42Xq+lwX8KyF5iT5kIxzYofUQgqRMJ35dS7PJYgH5Z
        kms_jwt_secret: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtmdnaT88qTqx34LFathd3AAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3FRTY1cSscoJ3RJXAgEQgCXSj1b6K5hdYdxvAF+VrpU//BJlg219NiTLIVwW1oDHTASAk8wn
        kms_key_id: 39f2c0c8-0941-46f2-a988-84af0ff9b5c6
        kms_key_region: us-east-1
        pm_auth_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
        podAnnotations:
          traffic_sidecar_istio_io_excludeOutboundIPRanges: 10.23.6.12/32
        recon_admin_api_key: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAFtdsNQJLAkmT+Y0eBJ/vQPAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDSQDb41cxE4RaEk2AgEQgCRYaHGWSFT6H8cBM6oHVsGaz+zoX0EAV+ytO3zD5ThVgOd7p4Y=
      secrets_manager: aws_kms
      server_base_url: https://sandbox.hyperswitch.io
      serviceAccountAnnotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::225681119357:role/hyperswitch-HyperswitchServiceAccountRoleCC06B446-hQ95y8j6lrm9
  autoscaling:
    enabled: true
    maxReplicas: 5
    minReplicas: 3
    targetCPUUtilizationPercentage: 80
  externalPostgresql:
    enabled: true
    primary:
      auth:
        database: hyperswitch
        password: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAGyPQxEsQIK1uOfA5KaXtnbAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDINTpWbj2Mvl/8DjAgEQgCMLgxXaUiSv+QpYABQQWHrv+7g6Hf76fQE+M4RWlE2ZT1+Qeg==
        plainpassword: Camel123
        username: db_user
      host: hyperswitch-hyperswitchdbcluster6afb6ee5-gjy30iebdhyo.cluster-ccpofvgo2wzr.us-east-1.rds.amazonaws.com
    readOnly:
      auth:
        database: hyperswitch
        password: AQICAHgJhH/UJmMAU4bCyCse9oi5A/Dj/fAfc1NvtN2Xez6PCAGyPQxEsQIK1uOfA5KaXtnbAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDINTpWbj2Mvl/8DjAgEQgCMLgxXaUiSv+QpYABQQWHrv+7g6Hf76fQE+M4RWlE2ZT1+Qeg==
        plainpassword: Camel123
        username: db_user
      host: hyperswitch-hyperswitchdbcluster6afb6ee5-gjy30iebdhyo.cluster-ro-ccpofvgo2wzr.us-east-1.rds.amazonaws.com
  externalRedis:
    enabled: true
    host: hs-elasticache.4x7hjl.0001.use1.cache.amazonaws.com
    port: 6379
  hyperswitch-card-vault:
    enabled: false
    postgresql:
      enabled: false
    server:
      secrets:
        locker_private_key: ""
        master_key: ""
        tenant_public_key: ""
  loadBalancer:
    targetSecurityGroup: sg-09af3d7cc4c51a625
  postgresql:
    enabled: false
  redis:
    enabled: false
  services:
    consumer:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-consumer:v1.107.0-standalone
    controlCenter:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-control-center:v1.29.9
    producer:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-producer:v1.107.0-standalone
    router:
      image: 225681119357.dkr.ecr.us-east-1.amazonaws.com/juspaydotin/hyperswitch-router:v1.107.0-standalone
    sdk:
      host: http://localhost:9090
      subversion: v0
      version: 0.27.2
hyperswitchsdk:
  autoBuild:
    forceBuild: true
    gitCloneParam:
      gitVersion: 0.27.2
    nginxConfig:
      extraPath: v0
  enabled: true
  ingress:
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
      alb.ingress.kubernetes.io/group.name: hyperswitch-web-alb-ingress-group
      alb.ingress.kubernetes.io/ip-address-type: ipv4
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/load-balancer-name: hyperswitch-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: sg-09af3d7cc4c51a625
      alb.ingress.kubernetes.io/tags: stack=hyperswitch-lb
      alb.ingress.kubernetes.io/target-type: ip
    className: alb
    hosts:
    - host: ""
      paths:
      - path: /
        pathType: Prefix
  loadBalancer:
    targetSecurityGroup: sg-09af3d7cc4c51a625
  services:
    router:
      host: http://localhost:8080
    sdkDemo:
      hyperswitchPublishableKey: pub_key
      hyperswitchSecretKey: secret_key
      image: juspaydotin/hyperswitch-web:v1.0.10
loadBalancer:
  targetSecurityGroup: sg-09af3d7cc4c51a625
