version: 0.2

phases:
  build:
    commands:
       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
       - |
        PULL_FROM_DOCKER=("grafana/grafana" "grafana/loki" "grafana/promtail" "grafana/fluent-bit-plugin-loki" "nginx" "juspaydotin/hyperswitch-router" "juspaydotin/hyperswitch-producer" "juspaydotin/hyperswitch-consumer" "juspaydotin/hyperswitch-control-center" "juspaydotin/hyperswitch-web", "bitnami/metrics-server")
        PULL_FROM_AWS=("eks/aws-load-balancer-controller" "ebs-csi-driver/aws-ebs-csi-driver" "eks-distro/kubernetes-csi/external-provisioner" "eks-distro/kubernetes-csi/external-attacher" "eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter" "eks-distro/kubernetes-csi/livenessprobe" "eks-distro/kubernetes-csi/external-resizer" "eks-distro/kubernetes-csi/node-driver-registrar" "ebs-csi-driver/volume-modifier-for-k8s")

        for IMAGE in "${PULL_FROM_DOCKER[@]}"; do
          aws ecr create-repository --repository-name $IMAGE --image-scanning-configuration scanOnPush=true
        done

        for IMAGE in "${PULL_FROM_K8S[@]}"; do
          aws ecr create-repository --repository-name $IMAGE --image-scanning-configuration scanOnPush=true
        done

        for IMAGE in "${PULL_FROM_AWS[@]}"; do
          aws ecr create-repository --repository-name $IMAGE --image-scanning-configuration scanOnPush=true
        done

        for IMAGE in "${PULL_FROM_DOCKER[@]}"; do
          if [[ $IMAGE == "juspaydotin/hyperswitch-router" || $IMAGE == "juspaydotin/hyperswitch-producer" || $IMAGE == "juspaydotin/hyperswitch-consumer" ]]; then
            docker pull $IMAGE:v1.105.0
            docker tag $IMAGE:v1.105.0 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.105.0
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.105.0
          elif [[ $IMAGE == "juspaydotin/hyperswitch-control-center" ]]; then
            docker pull $IMAGE:v1.17.0
            docker tag $IMAGE:v1.17.0 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.17.0
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.17.0
          elif [[ $IMAGE == "juspaydotin/hyperswitch-web" ]]; then
            docker pull $IMAGE:v1.0.4
            docker tag $IMAGE:v1.0.4 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.0.4
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.0.4
          elif [[ $IMAGE == "bitnami/metrics-server"]]
            docker pull $IMAGE:v0.7.0
            docker tag $IMAGE:v0.7.0 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v0.7.0
          else
            docker pull $IMAGE
            docker tag $IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE
          fi
        done

        for IMAGE in "${PULL_FROM_AWS[@]}"; do
          if [[ $IMAGE == "eks/aws-load-balancer-controller" ]]; then
            docker pull public.ecr.aws/$IMAGE:v2.7.1
            docker tag public.ecr.aws/$IMAGE:v2.7.1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v2.7.1
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v2.7.1
          elif [[ $IMAGE == "ebs-csi-driver/aws-ebs-csi-driver" ]]; then
            docker pull public.ecr.aws/$IMAGE:v1.28.0
            docker tag public.ecr.aws/$IMAGE:v1.28.0 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.28.0
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.28.0
          elif [[ $IMAGE == "eks-distro/kubernetes-csi/external-provisioner" ]]; then
            docker pull public.ecr.aws/$IMAGE:v4.0.0-eks-1-29-5
            docker tag public.ecr.aws/$IMAGE:v4.0.0-eks-1-29-5 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v4.0.0-eks-1-29-5
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v4.0.0-eks-1-29-5
          elif [[ $IMAGE == "eks-distro/kubernetes-csi/external-attacher" ]]; then
            docker pull public.ecr.aws/$IMAGE:v4.5.0-eks-1-29-5
            docker tag public.ecr.aws/$IMAGE:v4.5.0-eks-1-29-5 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v4.5.0-eks-1-29-5
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v4.5.0-eks-1-29-5
          elif [[ $IMAGE == "eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter" ]]; then
            docker pull public.ecr.aws/$IMAGE:v7.0.0-eks-1-29-5
            docker tag public.ecr.aws/$IMAGE:v7.0.0-eks-1-29-5 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v7.0.0-eks-1-29-5
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v7.0.0-eks-1-29-5
          elif [[ $IMAGE == "eks-distro/kubernetes-csi/livenessprobe" ]]; then
            docker pull public.ecr.aws/$IMAGE:v2.12.0-eks-1-29-5
            docker tag public.ecr.aws/$IMAGE:v2.12.0-eks-1-29-5 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v2.12.0-eks-1-29-5
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v2.12.0-eks-1-29-5
          elif [[ $IMAGE == "eks-distro/kubernetes-csi/external-resizer" ]]; then
            docker pull public.ecr.aws/$IMAGE:v1.10.0-eks-1-29-5
            docker tag public.ecr.aws/$IMAGE:v1.10.0-eks-1-29-5 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.10.0-eks-1-29-5
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v1.10.0-eks-1-29-5
          elif [[ $IMAGE == "eks-distro/kubernetes-csi/node-driver-registrar" ]]; then
            docker pull public.ecr.aws/$IMAGE:v2.10.0-eks-1-29-5
            docker tag public.ecr.aws/$IMAGE:v2.10.0-eks-1-29-5 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v2.10.0-eks-1-29-5
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v2.10.0-eks-1-29-5
          elif [[ $IMAGE == "ebs-csi-driver/volume-modifier-for-k8s" ]]; then
            docker pull public.ecr.aws/$IMAGE:v0.2.1
            docker tag public.ecr.aws/$IMAGE:v0.2.1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v0.2.1
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE:v0.2.1
          fi
        done

